services:
  # Sproutcast - Standalone (No MQTT)
  sproutcast:
    image: sproutcast/unified:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sc-app
    environment:
      # Camera Configuration
      - CAMERA_ID=0
      - INPUT_MODE=IMAGE
      - INPUT_PATH=/samples/plant.jpg
      
      # Disable MQTT by not setting MQTT_HOST
      # - MQTT_HOST=mqtt-broker  ← Commented out
      # - MQTT_PORT=1883
      
      # Processing Configuration
      - THRESHOLD=100
      - SCALE_PX_PER_CM=28.0
      - CONFIG_PATH=/app/data/config.json
      
      # Debug Settings
      - VISION_DEBUG_MODE=true
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"  # Web UI only
    volumes:
      - ./samples:/samples:ro
      - ./data:/app/data
      - ./models:/app/models:ro
    restart: unless-stopped

volumes: {}
