version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: sc-mqtt
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  cpp-app:
    image: sproutcast/cpp:latest
    build:
      context: ./cpp
      dockerfile: Dockerfile
    container_name: sc-cpp
    depends_on:
      - mqtt-broker
    environment:
      - CAMERA_ID=0
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=
      - PUBLISH_INTERVAL_MS=1000
      - THRESHOLD=100
      - INPUT_MODE=IMAGE
      - INPUT_PATH=/samples/plant.jpg
    volumes:
      - ./samples:/samples:ro
      - ./data:/app/data

  web-ui:
    image: sproutcast/web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: sc-web
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data

  ai:
    image: sproutcast/ai:latest
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: sc-ai
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
      - UNS_ROOM=room-1
      - UNS_AREA=area-1
      - CAMERA_ID=0
      - PLANT_ID=plant-1
    volumes:
      - ./data:/app/data
      - ./models:/app/models:ro

volumes: {}

