version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: pv-mqtt
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  cpp-app:
    image: plantvision/cpp:latest
    build:
      context: ./cpp
      dockerfile: Dockerfile
    container_name: pv-cpp
    depends_on:
      - mqtt-broker
    environment:
      - CAMERA_ID=0
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=plant/area
      - PUBLISH_INTERVAL_MS=1000
      - THRESHOLD=100
      - INPUT_MODE=IMAGE
      - INPUT_PATH=/samples/plant.jpg
    volumes:
      - ./samples:/samples:ro

  web-ui:
    image: plantvision/web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: pv-web
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

volumes: {}

