services:
  sproutcast:
    image: tahrit/sproutcast:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sproutcast
    environment:
      # Camera Configuration
      - CAMERA_ID=0
      - INPUT_MODE=IMAGE           # Use IMAGE for testing, CAMERA for production
      - INPUT_PATH=/samples/plant.jpg
      
      # MQTT Configuration (internal broker)
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - MQTT_TOPIC=sproutcast/area/greenhouse/camera
      - PUBLISH_INTERVAL_MS=30000
      
      # Processing Configuration
      - THRESHOLD=100
      - SCALE_PX_PER_CM=28.0
      - CONFIG_PATH=/app/data/config.json
      
      # Debug Settings
      - VISION_DEBUG_MODE=false
      - LOG_LEVEL=INFO
    ports:
      - "5323:5323"   # Web UI (LEAF = 5323 on phone keypad! 🌿)
      - "1883:1883"   # MQTT Broker
      - "9001:9001"   # MQTT WebSocket
    volumes:
      - ./samples:/samples:ro
      - ./data:/app/data
      - ./models:/app/models:ro
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    # Uncomment for Linux with camera access:
    # devices:
    #   - /dev/video0:/dev/video0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5323/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes: {}

