version: '3.8'

services:
  sproutcast:
    image: ghcr.io/tahrit/sproutcast:latest
    container_name: sproutcast-prod
    ports:
      - "5323:5323"   # Web UI (LEAF = 5323 on phone keypad! 🌿)
      - "1883:1883"   # MQTT Broker
      - "9001:9001"   # MQTT WebSocket
    volumes:
      - ./data:/app/data
      - ./models:/app/models:ro
      - ./logs:/app/logs
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    environment:
      - CAMERA_ID=0
      - INPUT_MODE=CAMERA
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - MQTT_TOPIC=sproutcast/area/greenhouse/camera
      - PUBLISH_INTERVAL_MS=30000
      - THRESHOLD=100
      - CONFIG_PATH=/app/data/config.json
      - VISION_DEBUG_MODE=false
      - LOG_LEVEL=INFO
      - SCALE_PX_PER_CM=28.0
      - MODEL_CACHE_DIR=/app/models
      - ENVIRONMENT=production
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5323/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
